### ISSUE TITLE
MAPE formula potential issue with array

### ISSUE THREAD

**Issue by Emnlv** [sibylhe/mmm_stan#21] opened 2021-02-23 10:55 UTC
Hi Sibyl.

Hoping you are fine. 
I have found a really strange situation that I want to share.

This formula:
```
def mean_absolute_percentage_error(y_true, y_pred): 
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

```
I have seen that if I am using the same value that is inside a DataFrame instead of an array, with the exact same values, results are totally different.

I will better explain, focusing on the calculation inside the formula mmm_decompose_contrib():
If you consider this: mc_df["y_true3"], mc_df["y_pred"] = y_true2, y_pred
np.mean(np.abs((np.array(mc_df["y_true3"]) - np.array(mc_df["y_pred"]))/np.array(mc_df["y_true3"]))) * 100
is totally different compared to np.mean(np.abs((np.array(y_true2) - np.array(y_pred)) / np.array(y_true2))) * 100

I have check it step by step. And the output of this step: 
np.abs((np.array(y_true2) - np.array(y_pred)) / np.array(y_true2)) it is not clear to me, because the output is a combination of array 
whilst the output of this :
np.abs((np.array(mc_df["y_true3"]) - np.array(mc_df["y_pred"]))/np.array(mc_df["y_true3"])) * 100 is a singular array, and it makes sense to me.

If it was an error, I suggest inside the formula mmm_decompose_contrib() to put the data required for the MAPE, into the mc_df and then to pass it through the formula.

**Comment by NichoGustafson** [comment] 2021-02-23 16:05
I'm not able to replicate this. 

`np.abs((np.array(y_true2) - np.array(y_pred)) / np.array(y_true2))`

Always yields a 1 dimensional array when y_true2 and y_pred are 1 dimensional arrays.

**Comment by sibylhe** [comment] 2021-02-23 18:14
I cannot reproduce this. Please provide a test case.

**Comment by sibylhe** [comment] 2021-02-28 05:04
Closing this since I cannot reproduce it. Feel free to reopen if you have any updates.

**Closed by sibylhe** 2021-02-28 05:04 UTC
